2023-07-31 15:19:42,861 | main_logger | MainProcess  |        <module>               | INFO  | Master execution started
2023-07-31 15:19:42,862 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the create_folder_structure function
2023-07-31 15:19:42,862 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the common_files_downloads function
2023-07-31 15:19:44,029 | main_logger | MainProcess  |        execute_pipeline_download | INFO  | calling the orchestrate_calling function
2023-07-31 15:19:44,032 | main_logger | MainProcess  |        task_orc_execution     | INFO  | execution at task level
2023-07-31 15:19:46,445 | main_logger | MainProcess  |        send_mail              | INFO  | mail sent
2023-07-31 15:19:51,888 | main_logger | MainProcess  |        task_orc_execution     | ERROR | error in orchestrate_task_calling 'config_path'.
Traceback (most recent call last):
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 608, in task_orc_execution
    execute_job(prj_nm,paths_data,task_nm,run_id,file_path,iter_value)
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 38, in execute_job
    raise error
  File "/home/nandishms/test/src/scripts/orchestration/orchestrate.py", line 35, in execute_job
    download.execute_engine(prj_nm,task_id,paths_data,run_id,file_path,iter_value)
  File "/home/nandishms/test/download.py", line 242, in execute_engine
    raise error
  File "/home/nandishms/test/download.py", line 238, in execute_engine
    engine_code.engine_main(prj_nm,task_name,config_path,run_id,file_path,iter_value)
  File "/home/nandishms/test//src/scripts/engine_main/engine_code.py", line 476, in engine_main
    raise error
  File "/home/nandishms/test//src/scripts/engine_main/engine_code.py", line 284, in engine_main
    config_file_path = os.path.expanduser(paths_data["folder_path"])+paths_data["config_path"]
KeyError: 'config_path'
2023-07-31 15:19:51,891 | main_logger | MainProcess  |        get_ind_task_status    | INFO  | rest_api_test task is FAILED
2023-07-31 15:19:51,891 | main_logger | MainProcess  |        task_orc_execution     | INFO  | Task rest_api_test Execution failed.
2023-07-31 15:19:55,079 | main_logger | MainProcess  |        send_mail              | INFO  | mail sent
